# Generated by Django 5.1.6 on 2025-02-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
