# Generated by Django 5.1.6 on 2025-02-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exams',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
    ]
